### ISSUE TITLE
关于初次使用提示

### ISSUE THREAD

**Issue by btr18** [xuejianxianzun/PBDWiki#1]
已经使用pbd挺久了，遇到过不少回设置重置却没发现，导致图全下到一个文件夹中的情况
直到今天下了两小时的图发现文件夹设置被初始化了，才忍不住来反馈一下
在初次使用时，能不能增加比较明显的初次使用提示，以让人知道是第一次使用/设置被重置了

**Comment by xuejianxianzun** [comment]
>遇到过不少回设置重置却没发现

你是否经常清除浏览器缓存？如果你清除了 `cookies 和其他网站数据`，下载器的设置也会被清除，所以会变成默认设置。
有些用户并不会去修改设置，可能很长时间都一直使用默认设置，这种提醒对他们来说是不必要的。你见过哪个软件上来先提示你去修改设置的吗？
我个人的建议是，你应该明白设置被重置的原因（在浏览器里新安装这个扩展，或者是清除了浏览器数据，或者手动重置设置）（前两种行为下载器无法控制，如果你手动重置则会有一次确认提示）。在发生了这些情况时你能够意识到设置会被重置，并进行处理。
你也可以修改设置之后导出设置，以便以后需要时导入设置。这些功能在下载器的“其他”选项卡里。

**Comment by xuejianxianzun** [comment]
另外你的命名规则是什么？
我觉得或许应该把默认命名规则改成 `{user}/{id}`，这样默认就会建立文件夹。
但这样会带来新的问题，比如在排行榜页面下载时，几百张图片可能对应几百个画师，你肯定不希望下载下来几百个文件夹，里面都只有一两张图片。这种情况下应该修改命名规则，但是很多用户并不明白，或者不会合理的设置。考虑到这个问题，对于如何修改默认命名规则，我也一筹莫展。
或许可以试试比较通用的  `{p_title}/{id}`，我想问问你的看法。

**Comment by btr18** [comment]
我通常使用pbd下载某一个画师的所有作品（或某作品后的作品），很少去下载排行榜，可能与别的用户用法不同我目前如此设置：pixiv/{user}/({id}) {title}
如果不在意图片文件名的用户比较多，或许可以尝试pixiv/{p_title}/[{user}]{id} 。可以直观搜索画师名或进入作品页面。即使是我这种建立画师文件夹的用户，遇到重置设定情况，也能通过everything很快分类开来
之前没使用过{p_title}，思考了一下，可能有如下缺点：下载某作品后的所有图片的情景（更新画师新图，或者对画师此前的图不感兴趣），文件夹就会以该作品的标题命名


不是很相关的内容：
之前没注意规则重置了，下载了4600+只带有pid的图片，现在打算尝试做这么一个程序，来尝试急救一下：
读取文件名（pid），然后搜索画师名称，移动到对应画师名的文件夹中（没有则创建）
我没有编程基础，有朋友跟我说读取、创建和移动比较简单，搜索画师名比较复杂，但也有api可以调用。总之自己正在尝试中。。。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月11日(星期二) 下午2:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xuejianxianzun/PBDWiki] 关于初次使用提示 (#1)





 
另外你的命名规则是什么？
 我觉得或许应该把默认命名规则改成 {user}/{id}，这样默认就会建立文件夹。
 但这样会带来新的问题，比如在排行榜页面下载时，几百张图片可能对应几百个画师，你肯定不希望下载下来几百个文件夹，里面都只有一两张图片。这种情况下应该修改命名规则，但是很多用户并不明白，或者不会合理的设置。考虑到这个问题，对于如何修改默认命名规则，我也一筹莫展。
 或许可以试试比较通用的  {p_title}/{id}，我想问问你的看法。
 
&mdash;

**Comment by xuejianxianzun** [comment]
已经过去5个月了，现在在第一次进行下载时，下载器会弹出提示。清除数据也会重置这个提示，所以你可以发现设置被重置的问题。
另外现在也可以在不同页面使用不同的（独立的）命名规则了。这个问题应该算解决了。
