### ISSUE TITLE
关于清理硬盘后继续下载的问题

### ISSUE THREAD

**Issue by idbtr1** [xuejianxianzun/PBDWiki#2]
最近遇到几次下载画师图片过程中，因为硬盘满了而停止的情况
在清理出足够空间后，继续下载，会仍然提示硬盘已满
无论是停止后重新下载，还是重启浏览器后重新抓取，都没法继续下载图片
![image](https://user-images.githubusercontent.com/85356188/137525012-397ca3fd-72a7-4f84-a0c7-9d80bbb96162.png)

**Comment by xuejianxianzun** [comment]
这个提示是Chrome的策略导致的，系统盘剩余空间不足时，Chrome会直接取消掉对一些大文件的XHR（下载）请求，所以会出现卡住的情况，下载流程会反复暂停、重试，在经过多次尝试后下载器会弹出这个提示。
鉴于你的C盘空间较小，我觉得还是有可能是你硬盘空间的问题。
首先你可以重启浏览器（或者重启系统），然后打开这个页面继续下载。如果可以下载，说明问题暂时解决。
如果问题仍然存在，还请继续清理一些空间试试（例如把页面文件、一些软件、文件挪到其他盘），然后重启浏览器看能否下载。
期待你的反馈。

**Comment by xuejianxianzun** [comment]
如果不是硬盘问题，则可能是网络代理（软件）导致的问题。由于你太久没回复，这个问题将被关闭。
