### ISSUE TITLE
怎么在预览图上显示已收藏该画师，以前有的莫名其妙没了

### ISSUE THREAD

**Issue by puinpuni** [xuejianxianzun/PBDWiki#3]
怎么在预览图上显示已收藏该画师，以前有的莫名其妙没了

**Comment by xuejianxianzun** [comment]
你是说这种吗？还是其他什么地方？
![QQ截图20211120113640.jpg](https://i.loli.net/2021/11/20/qOHcleETW5BNJ6s.jpg)
上图是p站控制的，和下载器无关。在有些页面有，有些页面没有。

**Comment by puinpuni** [comment]
![HBW`DJENR%1UGQH ILNJUK](https://user-images.githubusercontent.com/49758099/142713369-e9bd9ecc-d3cd-4a45-8be2-bac7baf4971c.png)
不是，预览图会变黑一点，右下角红框这里会显示该作家已收藏（粉底黑字）

**Comment by xuejianxianzun** [comment]
确认是“该作家已收藏”这几个字？那我只能猜测是你用了别的扩展/脚本。我的下载器没有此功能。

**Comment by puinpuni** [comment]
OK，那我在研究研究
